title: Security
icon: mdi:security
path: security
visible:
  - user: de9bffd1c5bb4136bdf12e68766b0c2d
#  - user: de9bffd1c5bb4136bdf12e68766b0c2c # simon
#  - user: ded1dc2c5ea24fffae588287678b3172
cards:
  - type: vertical-stack
    cards:
      - type: picture-entity
        title: Doorbell
        show_name: false
        show_state: false
        entity: camera.doorbell
      - type: picture-entity
        title: Front CCTV
        show_name: false
        show_state: false
        entity: camera.frigate_rtmp_front
      - type: picture-entity
        title: Rear CCTV
        show_name: false
        show_state: false
        entity: camera.frigate_rtmp_back
      - type: picture-entity
        title: Front door
        show_name: false
        show_state: false
        entity: camera.frigate_rtmp_door
      - type: conditional
        conditions:
          - entity: binary_sensor.people_home
            state: "off"
        card:
          type: vertical-stack
          cards:
            - type: picture-entity
              title: Kitchen
              show_name: false
              show_state: false
              entity: camera.frigate_rtmp_kitchen
            - type: picture-entity
              title: Lounge
              show_name: false
              show_state: false
              entity: camera.frigate_rtmp_lounge
            - type: picture-entity
              title: Lounge 2
              show_name: false
              show_state: false
              entity: camera.lounge2
