title: Security
icon: mdi:security
path: security
visible:
  - user: de9bffd1c5bb4136bdf12e68766b0c2c
  - user: ded1dc2c5ea24fffae588287678b3172
popup_cards:
  sensor.hacs: !include popup_cards/wifi_card.yaml
cards:
  - type: vertical-stack
    cards:
      - type: picture-entity
        title: Front CCTV
        show_name: false
        show_state: false
        entity: camera.frigate_rtmp_front
      - type: picture-entity
        title: Rear CCTV
        show_name: false
        show_state: false
        entity: camera.frigate_rtmp_back
      - type: picture-entity
        title: Front door
        show_name: false
        show_state: false
        entity: camera.frigate_rtmp_door
  - type: conditional
    conditions:
      - entity: binary_sensor.people_home
        state: "off"
    card:
      type: vertical-stack
      cards:
        - type: picture-entity
          title: Kitchen
          show_name: false
          show_state: false
          entity: camera.frigate_rtmp_kitchen
        - type: picture-entity
          title: Lounge
          show_name: false
          show_state: false
          entity: camera.frigate_rtmp_lounge
  - type: vertical-stack
    cards:
      - type: entities
        title: External motion detection
        show_header_toggle: true
        entities:
          - type: buttons
            entities:
              - entity: input_boolean.frigate_front_detect_state
                name: Front camera
              - entity: input_boolean.frigate_back_detect_state
                name: Rear camera
              - entity: input_boolean.frigate_door_detect_state
                name: Door camera
      - type: entities
        title: Internal motion detection
        show_header_toggle: true
        entities:
          - type: buttons
            entities:
              - entity: input_boolean.frigate_kitchen_detect_state
                name: Kitchen camera
              - entity: input_boolean.frigate_lounge_detect_state
                name: Lounge camera
      - type: "custom:card-templater"
        card:
          type: button
          entity: sensor.hacs
          name: "WiFi details"
          icon: "mdi:wifi-lock"
          state_color: false
          double_tap_action:
            action: none
          hold_action:
            action: none
