title: Security
icon: mdi:security
path: security
cards:
- type: vertical-stack
  cards:
    - type: picture-entity
      title: Front CCTV
      show_name: false
      show_state: false
      entity: camera.frigate_rtmp_front
    - type: picture-entity
      title: Rear CCTV
      show_name: false
      show_state: false
      entity: camera.frigate_rtmp_back
    - type: picture-entity
      title: Front door
      show_name: false
      show_state: false
      entity: camera.frigate_rtmp_door
- type: conditional
  conditions:
    - entity: binary_sensor.people_home
      state: "off"
  card:
    type: vertical-stack
    cards:
    - type: picture-entity
      title: Kitchen
      show_name: false
      show_state: false
      entity: camera.frigate_rtmp_kitchen
    - type: picture-entity
      title: Lounge
      show_name: false
      show_state: false
      entity: camera.frigate_rtmp_lounge
- type: vertical-stack
  cards:
    - type: entities
      title: External motion detection
      show_header_toggle: true
      entities:
        - type: buttons
          entities:
            - entity: input_boolean.frigate_front_motion_detection
              name: Front camera
            - entity: input_boolean.frigate_back_motion_detection
              name: Rear camera
            - entity: input_boolean.frigate_door_motion_detection
              name: Door camera
    - type: entities
      title: Internal motion detection
      show_header_toggle: true
      entitiies:
        - type: buttons
          entities:
            - entity: input_boolean.frigate_kitchen_motion_detection
              name: Kitchen camera
            - entity: input_boolean.frigate_lounge_motion_detection
              name: Lounge camera
