- alias: 'Presence simulation started'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:10:00'
  condition:
    condition: state
    entity_id: input_boolean.holiday_mode
    state: 'on'
  action:
    - delay: '00:{{ (range(10, 50)|random|int) }}:00'
    - service: notify.simons_pushbullet_notifier
      data:
        message: Away mode starting
        target: device/Houston
    - service: scene.turn_on
      entity_id: scene.kitchen_away_mode_on
    - delay: '00:{{ (range(2, 5)|random|int) }}:00'
    - service: scene.turn_on
      entity_id: scene.lounge_away_mode_on
    - service: notify.simons_pushbullet_notifier
      data:
        message: Away mode active
        target: device/Houston

- alias: 'Presence simulation stopped'
  trigger:
    platform: time
    at: '22:00:00'
  condition:
    condition: state
    entity_id: input_boolean.holiday_mode
    state: 'on'
  action:
    - delay: '00:{{ (range(25, 55)|random|int) }}:00'
    - service: notify.simons_pushbullet_notifier
      data:
        message: Away mode stopping
        target: device/Houston
    - service: scene.turn_on
      entity_id: scene.lounge_away_mode_off
    - delay: '00:{{ (range(1, 4)|random|int) }}:00'
    - service: scene.turn_on
      entity_id: scene.kitchen_away_mode_off
    - service: notify.simons_pushbullet_notifier
      data:
        message: Away mode deactivated
        target: device/Houston

- alias: 'Disable holiday mode'
  trigger:
    platform: state
    entity_id: device_tracker.simon, device_tracker.nikki
    from: 'not_home'
    to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.holiday_mode
    state: 'on'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.holiday_mode
