- platform: generic
  name: Kitchen Overview
  still_image_url: !secret kitchen_cam1_url
- platform: generic
  name: Nugget Flap
  still_image_url: !secret kitchen_cam2_url
- platform: uvc
  nvr: 10.101.0.50
  key: !secret nvr_key