homeassistant:
  name: Room101
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 35
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/London
  customize: !include customise.yaml

lovelace:
  mode: yaml

http:
  api_password: !secret http_password
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.101.0.30

config:
map:
updater:
conversation:
history:
logbook:
sun:
ffmpeg:

recorder:
  # Delete events and states older than 2 weeks
  purge_interval: 2
  purge_keep_days: 7
  exclude:
    domains:
      - automation
    entities:
      - sun.sun
      - sensor.date
      - sensor.time
      - sensor.pws_wind_string
      - sensor.pws_wind_mph
      - sensor.pws_weather_4n_metric
      - sensor.pws_weather_4d_metric
      - sensor.pws_weather_3n_metric
      - sensor.pws_weather_3d_metric
      - sensor.pws_weather_2n_metric
      - sensor.pws_weather_2d_metric
      - sensor.pws_weather_1n_metric
      - sensor.pws_weather_2d_metric
      - sensor.pws_temp_low_1d_c
      - sensor.pws_temp_high_1d_c
      - sensor.pws_temp_c
      - sensor.pws_relative_humidity
      - sensor.pws_pressure_mb
      - sensor.pws_precip_today_metric
      - sensor.pws_feelslike_c
      - sensor.pws_alerts
      - sensor.portsmouth_tides
      - sensor.waterloo__city
      - sensor.victoria
      - sensor.piccadilly
      - sensor.northern
      - sensor.metropolitan
      - sensor.jubilee
      - sensor.hammersmith__city
      - sensor.dlr
      - sensor.district
      - sensor.circle
      - sensor.central
      - sensor.bakerloo
      - sensor.highwood_crescent_eta

frontend:
  javascript_version: latest
  themes:
    greens:
      dark-primary-color: "#009688"
      primary-color: "#009688"
      light-primary-color: "#009688"
      paper-toggle-button-checked-ink-color: "#009688"
      paper-toggle-button-checked-button-color: "#009688"
      paper-toggle-button-checked-bar-color: "#99d5cf"
      paper-slider-knob-color: "#66c0b7"
      paper-slider-knob-start-color: "#32ab9f"
      paper-slider-pin-color: "#66c0b7"
      paper-slider-active-color: "#009688"
      paper-slider-secondary-color: "#009688"

zone:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  radius: 70
  icon: mdi:home

zone 2:
  name: Simon (Work)
  latitude: !secret simon_work_lat
  longitude: !secret simon_work_long
  radius: 250
  icon: mdi:laptop

zone 3:
  name: Nikki (Work)
  latitude: !secret nikki_work_lat
  longitude: !secret nikki_work_long
  icon: mdi:laptop

hue:
  bridges:
    - host: 10.101.0.178
      allow_unreachable: true
      allow_hue_groups: false

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: 78:11:dc:b1:f7:66
      key: !secret aqara_gateway_key

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
#  expose_by_default: true
  exposed_domains:
    - switch
    - input_boolean
    - media_player
#  entity_config:
#    light.gateway_light_7811dcb1f766:
#      name: understairs cupboard
#      aliases:
#        - understairs cupboard light
#        - gateway light
#    group.energenie_switches:
#      name: ambient switches
#    switch.energenie_one:
#      name: drinks cabinet
#    switch.energenie_two:
#      name: garden room
#      aliases:
#        - garden room twigs
#        - twigs
#    switch.energenie_three:
#      name: firefly lights
#      aliases:
#        - boat bookcase
#    switch.flux_adjustment:
#      name: living room colour adjustment
#      aliases:
#        - living room redshift
#        - living room flux
#    switch.loft_lighting:
#      name: loft lights
#    input_boolean.lounge_media_dim_enable:
#      name: media dimming
#    input_boolean.kodi_amp_trigger:
#      name: amp trigger
#    input_boolean.global_away_mode_toggle:
#      name: away mode
#    input_boolean.holiday_mode:
#      name: holiday mode
#    input_boolean.party_mode:
#      name: party mode
#    input_boolean.night_mode_toggle:
#      name: night mode
#    media_player.kodi:
#      name: kodi
#    media_player.garden_room:
#      name: garden room sonos
#    media_player.living_room:
#      name: living room sonos
#    media_player.kitchen:
#      name: kitchen sonos
#    media_player.denon_avrx2100w:
#      name: living room amp

#google:
#  client_id: !secret google_client_id
#  client_secret: !secret google_client_secret
#  track_new_calendar: false

prometheus:
  namespace: hass

mqtt:
  broker: !secret ip_mqtt_broker
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pass

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

zoneminder:
  host: !secret zoneminder_host
  username: !secret zoneminder_user
  password: !secret zoneminder_pass

input_boolean: !include inputs/boolean.yaml
input_number: !include inputs/numbers.yaml
input_select: !include inputs/select.yaml
notify: !include_dir_merge_list notify
media_player: !include media_players.yaml
light: !include lights.yaml
device_tracker: !include device_trackers.yaml
camera: !include cameras.yaml
sensor: !include sensors.yaml
binary_sensor: !include sensors/binary.yaml
switch: !include switches.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations
scene: !include scenes.yaml
script: !include_dir_merge_named scripts
