homeassistant:
  name: Room101
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 35
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/London
  customize: !include customise.yaml
  external_url: !secret base_url_with_scheme
  internal_url: !secret base_url_with_scheme
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

lovelace:
  mode: yaml
  resources: !include lovelace/zz_resources.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.25.0.64/27

logger:
  default: warn

config:
map:
updater:
conversation:
history:
logbook:
sun:
ffmpeg:
mobile_app:
media_source:
zeroconf:

recorder:
  purge_keep_days: 2
  include:
    domains:
      - sensor
      - switch
      - media_player

person:
  - name: Simon
    id: simon0000
    device_trackers:
      - device_tracker.houston_2
  - name: Nikki
    id: niki0000
    device_trackers:
      - device_tracker.galaxy_s10

tts:
  - platform: google_translate
    base_url: http://10.101.0.45:8123
  - platform: google_cloud
    key_file: secrets/google-cloud-tts.json
    voice: en-GB-Standard-A
    profiles:
      - small-bluetooth-speaker-class-device

google_assistant:
  project_id: !secret google_assistant_project_id
  report_state: true
  expose_by_default: false
  service_account: !include secrets/google-assistant.json
  entity_config:
    # tradfri pc power outlet
    switch.0x086bd7fffe19c5dd_switch:
      name: PC power
    # tradfri desk power outlet
    switch.0x000d6ffffe2a5801:
      name: desk
      aliases: desk power
      room: office
    light.0x000d6ffffe07b722:
      name: office desk lamp
      aliases: office desk light
      room: office
    switch.0x804b50fffea7f978:
      name: understairs cupboard
      aliases: understairs cupboard light
      room: "Understairs cupboard"
    # night mode toggle
    input_boolean.night_mode_toggle:
      name: night mode
    # kitchen under-cabinet lights
    switch.0x00124b0024c04605:
      name: "under cabinet lights"
      aliases: "under cabinets"
      room: kitchen

mqtt:
  broker: !secret ip_mqtt_broker
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pass
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

# enable thomasloven/hass-browser_mod
browser_mod:

octopusagile:
  region_code: "J"
  mpan: !secret octopus_mpan
  serial: !secret octopus_serial
  auth: !secret octopus_auth
  startdate: "2021-02-18"

google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret
  track_new_calendar: false

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id

input_boolean: !include inputs/boolean.yaml
input_number: !include inputs/numbers.yaml
input_select: !include inputs/select.yaml
input_datetime: !include inputs/datetime.yaml
input_text: !include inputs/text.yaml
notify: !include_dir_merge_list notify
light: !include lights.yaml
device_tracker: !include device_trackers.yaml
camera: !include cameras.yaml
calendar: !include calendars.yaml
sensor: !include sensors.yaml
binary_sensor: !include sensors/binary.yaml
switch: !include switches.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations
scene: !include scenes.yaml
script: !include_dir_merge_named scripts
timer: !include_dir_merge_named timers
shell_command: !include_dir_merge_named shell_command
