homeassistant:
  name: Room101
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 35
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/London
  customize: !include customise.yaml
  external_url: !secret base_url_with_scheme
  internal_url: !secret base_url_with_scheme
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  resources: !include lovelace/zz_resources.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.101.0.30
    - 10.101.0.60

logger:
  default: warning
  logs:
    hacs: debug
#    homeassistant.components.device_tracker: debug

config:
map:
updater:
conversation:
history:
logbook:
sun:
ffmpeg:
mobile_app:
media_source:
zeroconf:

recorder:
  purge_keep_days: 2
  include:
    domains:
      - sensor
      - switch
      - media_player

zone 3:
  name: Nikki (Work)
  latitude: !secret nikki_work_lat
  longitude: !secret nikki_work_long
  icon: mdi:laptop

person:
  - name: Simon
    id: simon0000
    device_trackers:
      - device_tracker.houston_2
  - name: Nikki
    id: niki0000
    device_trackers:
      - device_tracker.galaxy_s10

tts:
  - platform: google_translate
    base_url: http://10.101.0.45:8123
  - platform: google_cloud
    key_file: secrets/google-cloud-tts.json
    voice: en-GB-Standard-A
    profiles:
      - small-bluetooth-speaker-class-device

hue:
  bridges:
    - host: 10.101.0.178
      allow_unreachable: true
      allow_hue_groups: false

google_assistant:
  project_id: !secret google_assistant_project_id
  report_state: true
  expose_by_default: false
  service_account: !include secrets/google-assistant.json
  entity_config:
    # tradfri pc power outlet
    switch.0x086bd7fffe19c5dd_switch:
      name: PC power
    # tradfri desk power outlet
    switch.0x000d6ffffe2a5801:
      name: desk
      aliases: desk power
      room: office
    light.0x000d6ffffe07b722:
      name: office desk lamp
      aliases: office desk light
      room: office
    switch.0x804b50fffea7f978:
      name: understairs cupboard
      aliases: understairs cupboard light
      room: "Understairs cupboard"
    # night mode toggle
    input_boolean.night_mode_toggle:
      name: night mode

#prometheus:
#  namespace: hass

mqtt:
  broker: !secret ip_mqtt_broker
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pass
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

tradfri:
  host: !secret ip_tradfri

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

# enable thomasloven/hass-browser_mod
browser_mod:

octopusagile:
  region_code: "J"
  mpan: 2000056101249
  serial: 19L3668546
  auth: sk_live_dGdfiDmDwfxtLLHotSh123Et
  startdate: "2021-02-18"

google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret
  track_new_calendar: false

#spotcast:
#  sp_dc: !secret spotcast_dc_simon
#  sp_key: !secret spotcast_key_simon
#  accounts:
#    simon:
#      sp_dc: !secret spotcast_dc_simon
#      sp_key: !secret spotcast_key_simon
#    nikki:
#      sp_dc: !secret spotcast_dc_nikki
#      sp_key: !secret spotcast_key_nikki

input_boolean: !include inputs/boolean.yaml
input_number: !include inputs/numbers.yaml
input_select: !include inputs/select.yaml
input_datetime: !include inputs/datetime.yaml
input_text: !include inputs/text.yaml
notify: !include_dir_merge_list notify
light: !include lights.yaml
device_tracker: !include device_trackers.yaml
camera: !include cameras.yaml
calendar: !include calendars.yaml
sensor: !include sensors.yaml
binary_sensor: !include sensors/binary.yaml
switch: !include switches.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations
scene: !include scenes.yaml
script: !include_dir_merge_named scripts
timer: !include_dir_merge_named timers
shell_command: !include_dir_merge_named shell_command
