homeassistant:
  name: Room101
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 35
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/London
  customize: !include customise.yaml

# Enables the frontend
frontend:
  themes:
    greens:
      dark-primary-color: "#009688"
      primary-color: "#009688"
      light-primary-color: "#009688"
      paper-toggle-button-checked-ink-color: "#009688"
      paper-toggle-button-checked-button-color: "#009688"
      paper-toggle-button-checked-bar-color: "#99d5cf"
      paper-slider-knob-color: "#66c0b7"
      paper-slider-knob-start-color: "#32ab9f"
      paper-slider-pin-color: "#66c0b7"
      paper-slider-active-color: "#009688"
      paper-slider-secondary-color: "#009688"

zone:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  icon: mdi:home

zone 2:
  name: Simon (Work)
  latitude: !secret simon_work_lat
  longitude: !secret simon_work_long
  icon: mdi:laptop

zone 3:
  name: Nikki (Work)
  latitude: !secret nikki_work_lat
  longitude: !secret nikki_work_long
  icon: mdi:laptop

# Enables configuration UI
config:

# enable map panel
map:

http:
  api_password: !secret http_password
  base_url: !secret base_url
  use_x_forwarded_for: true

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: 78:11:dc:b1:f7:66
      key: 757C90A939F44F11

google_assistant:
  project_id: home-assistant-177620
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  expose_by_default: true

tts:
  platform: google

input_boolean: !include inputs/boolean.yaml
input_number: !include inputs/numbers.yaml
input_select: !include inputs/select.yaml
input_text: !include inputs/text.yaml

updater:
conversation:
history:
logbook:
sun:

emulated_hue:
  host_ip: 10.101.0.45
  listen_port: 8300
  advertise_ip: 10.101.0.45
  advertise_port: 1901
  upnp_bind_multicast: false
  expose_by_default: true
  exposed_domains:
    - input_boolean

mqtt:
  broker: !secret ip_mqtt_broker
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pass

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

notify: !include_dir_merge_list notify
media_player: !include media_players.yaml
light: !include lights.yaml
device_tracker: !include device_trackers.yaml
camera: !include cameras.yaml
sensor: !include sensors.yaml
binary_sensor: !include sensors/binary.yaml
switch: !include switches.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations
scene: !include scenes.yaml
script: !include_dir_merge_named scripts
