- platform: unifi
  username: admin
  password: !secret unifi_pass
  host: !secret unifi_host
  port: !secret unifi_port
  verify_ssl: false
  site_id: !secret unifi_site
  track_new_devices: false
  detection_time: 600
- platform: owntracks_http
  max_gps_accuracy: 200
  waypoint_whitelist:
    - simon
    - nikki
- platform: ping
  hosts:
    simon_iphone_ping: 10.101.0.201
