- platform: kodi
  host: !secret ip_kodi
  port: 8080
  tcp_port: 9090
  enable_websocket: true
- platform: philips_android_tv
  name: Philips 65OLED805
  host: !secret ip_philips_tv
  mac: !secret philips_tv_mac
  username: !secret philips_tv_username
  password: !secret philips_tv_password
