  #- platform: cast
  #host: !secret ip_ccast_1
  #- platform: cast
  #host: !secret ip_ccast_2
  #- platform: plex
  #show_all_controls: true
  #use_custom_entity_ids: true
  #entity_namespace: 'plex'
- platform: kodi
  host: !secret ip_kodi
  port: 8080
  tcp_port: 9090
  enable_websocket: true
- platform: samsungtv
  host: !secret ip_samsung
- platform: denonavr
  host: !secret ip_denon
  name: Denon AVRX2100W
  show_all_sources: true
