- platform: kodi
  host: !secret ip_kodi
  port: 8080
  tcp_port: 9090
  enable_websocket: true
#- platform: denonavr
#  host: !secret ip_denon
#  name: Denon AVRX2100W
#  show_all_sources: true
- platform: philips_js
  host: !secret ip_philips_tv
