- platform: time_date
  display_options:
    - time
- platform: waste_collection_schedule
  name: "Bin collections"
  leadtime: 20
- platform: template
  sensors:
    simon_status:
      value_template: '{{ states.input_select.simon_status.state }}'
      friendly_name: 'Simon'
    nikki_status:
      value_template: '{{ states.input_select.nikki_status.state }}'
      friendly_name: 'Nikki'
- platform: template
  sensors:
    external_doors_open:
      friendly_name: 'External doors open'
      value_template: >-
        {{ ['binary_sensor.0x00158d0001de662f_contact', 'binary_sensor.0x00158d0001a3e090_contact'] | select('is_state', 'on') | list | count }}
    windows_open:
      friendly_name: 'Windows open'
      value_template: >-
        {{ states.binary_sensor | selectattr('state', 'eq', 'on') | selectattr('attributes.friendly_name', 'match', '.*window.*') | list | count }}
- platform: template
  sensors:
    count_included_lights_on:
      friendly_name: 'Count included lights on'
      value_template: >-
        {% set data = namespace(lights_on=[]) %}
        {% set all_lights = states.light | rejectattr('attributes.entity_id', 'defined') | map(attribute='entity_id') | list %}
        {% set excluded_lights = label_entities('exclude_from_templates') %}
        {% for light in all_lights %}
        {% if is_state(light, 'on') %}
        {% if light not in excluded_lights %}
        {% set data.lights_on = data.lights_on + [light] %}
        {% endif %}
        {% endif %}
        {% endfor %}
        {{ data.lights_on | count }}
- platform: template
  sensors:
    count_sonoses_playing:
      friendly_name: 'Count Sonos devices currently playing'
      value_template: >-
        {% set data = namespace(devices_playing=[]) %}
        {% set all_devices = states.media_player | rejectattr('attributes.entity_id', 'defined') | map(attribute='entity_id') | list %}
        {% set included_devices = label_entities('is_sonos') %}
        {% for device in all_devices %}
        {% if is_state(device, 'playing') %}
        {% if device in included_devices %}
        {% set data.devices_playing = data.devices_playing + [device] %}
        {% endif %}
        {% endif %}
        {% endfor %}
        {{ data.devices_playing | count }}
- platform: template
  sensors:
    bin_collection_days_to:
      friendly_name: 'Days to next bin collection'
      value_template: >
        {% set now = today_at() %}
        {% set bin_day = state_attr('calendar.horsham_district_council', 'start_time') | as_datetime | as_local %}
        {% set delta = bin_day - now %}
        {{delta.days}}
- platform: template
  sensors:
    door_front_door:
      friendly_name: 'Front door'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001a1f6b9', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001a1f6b9', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    door_patio_door:
      friendly_name: 'Patio door'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001a3e090', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001a3e090', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    door_living_room_door:
      friendly_name: 'Living room door'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d000346b47f', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001a3e090', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    window_living_room:
      friendly_name: 'Living room window'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001b70752', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001b70752', 'on') %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}
    window_kitchen_left:
      friendly_name: 'Kitchen window (left)'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001e4820c', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001e4820c', 'on') %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}
    window_kitchen_right:
      friendly_name: 'Kitchen window (right)'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001de662f', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001de662f', 'on') %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}
