- platform: time_date
  display_options:
    - time
- platform: template
  sensors:
    simon_status:
      value_template: '{{ states.input_select.simon_status.state }}'
      friendly_name: 'Simon'
    nikki_status:
      value_template: '{{ states.input_select.nikki_status.state }}'
      friendly_name: 'Nikki'
- platform: template
  sensors:
    door_front_door:
      friendly_name: 'Front door'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001a1f6b9', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001a1f6b9', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    door_patio_door:
      friendly_name: 'Patio door'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001a3e090', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001a3e090', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    door_living_room_door:
      friendly_name: 'Living room door'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d000346b47f', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001a3e090', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    window_living_room:
      friendly_name: 'Living room window'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001b70752', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001b70752', 'on') %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}
    window_kitchen_left:
      friendly_name: 'Kitchen window (left)'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001e4820c', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001e4820c', 'on') %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}
    window_kitchen_right:
      friendly_name: 'Kitchen window (right)'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001de662f', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001de662f', 'on') %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}
- platform: template
  sensors:
    m3_remaining_range_fuel_miles:
      friendly_name: "M3 remaining range fuel (miles)"
      unit_of_measurement: 'miles'
      value_template: "{{ states('sensor.m3_remaining_range_fuel') | float / 1.609 | round(0) }}"
      icon_template: "mdi:gas-station"
