- platform: time_date
  display_options:
    - time
- platform: template
  sensors:
    simon_status:
      value_template: '{{ states.input_select.simon_status.state }}'
      friendly_name: 'Simon'
    nikki_status:
      value_template: '{{ states.input_select.nikki_status.state }}'
      friendly_name: 'Nikki'
- platform: template
  sensors:
    door_front_door:
      friendly_name: 'Front door'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001a1f6b9', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001a1f6b9', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    door_patio_door:
      friendly_name: 'Patio door'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001a3e090', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001a3e090', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    door_living_room_door:
      friendly_name: 'Living room door'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d000346b47f', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001a3e090', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    window_living_room:
      friendly_name: 'Living room window'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001b70752', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001b70752', 'on') %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}
    window_kitchen_left:
      friendly_name: 'Kitchen window (left)'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001e4820c', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001e4820c', 'on') %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}
    window_kitchen_right:
      friendly_name: 'Kitchen window (right)'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001de662f', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001de662f', 'on') %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}
- platform: template
  - sensor:
    - unique_id: sidebar_greeting
      state: template
      attributes:
        time: >
          {% set hours = now().strftime('%H') %}
          {% set minutes = now().strftime('%M') %}
          <span class="time">
            {{ hours }}<span class="time-colon">:</span>{{ minutes }}
          </span>
        date: |
          <font color='#6a7377'><b>
          {%- if strptime(states('sensor.date'), '%Y-%m-%d').day != null %}
          {%- set days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %}
          {%- set months = ['January', 'February', 'March', 'April', 'May', 'June', 
          'July', 'August', 'September', 'October', 'November', 'December'] %}
            {{- days[now().weekday()] }}<br>
            {{- strptime(states('sensor.date'), '%Y-%m-%d').day }} {{ months[now().month-1] }}
          {%- endif -%}
          </b></font>
        greeting: |
          <b>
          {%- set time = now().hour %}
          {%- if time <= 1 -%} Good night {{'\U0001F611'}}
          {%- elif time <= 3 -%} Good night {{'\U0001F62A'}}
          {%- elif time <= 5 -%} Good night {{'\U0001F634'}}
          {%- elif time <= 7 -%} Good morning {{'\U0001F4A9'}}
          {%- elif time <= 9 -%} Good morning {{'\u2615\uFE0F'}}
          {%- elif time <= 10 -%} Good morning {{'\U0001F642'}}
          {%- elif time <= 13 -%} Good day {{'\U0001F60A'}}
          {%- elif time <= 15 -%} Good day {{'\U0001F60E'}}
          {%- elif time <= 17 -%} Good day {{'\U0001F44B\U0001F3FB'}}
          {%- elif time <= 19 -%} Good evening {{'\U0001F44B\U0001F3FB'}}
          {%- elif time <= 22 -%} Good evening {{'\U0001F60C'}}
          {%- elif time <= 23 -%} Good night {{'\U0001F974'}}
          {%- else %} Good night {{'\U0001F974'}}
          {%- endif -%}
          </b>
# zigbee2mqtt: monitor the bridge state
- platform: mqtt
  name: Zigbee2MQTT bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless
# zigbee2mqtt: show version
- platform: mqtt
  name: Zigbee2MQTT version
  state_topic: "zigbee2mqtt/bridge/config"
  value_template: "{{ value_json.version }}"
  icon: mdi:zigbee
# zigbee2mqtt: coordinator version
- platform: mqtt
  name: Coordinator version
  state_topic: "zigbee2mqtt/bridge/config"
  value_template: "{{ value_json.coordinator }}"
  icon: mdi:chip
# average kitchen illuminance
- platform: min_max
  entity_ids:
    - sensor.0x00158d000237acbc_illuminance_lux
    - sensor.0x00158d0002b7f000_illuminance_lux
  type: mean
  name: 'Kitchen brightness'
  round_digits: 1

# enable octopus agile
- platform: "octopusagile"
