- platform: yr
  name: Weather
  monitored_conditions:
    - symbol
#- platform: plex
#  host: 10.101.0.50
#  port: 32400
#  username: !secret local_plex_username
#  password: !secret local_plex_password
- platform: command_line
  command: curl -s http://10.101.0.47:5000/api/envirophat/weather/temperature
  name: Loft temperature
  unit_of_measurement: "C"
- platform: command_line
  command: curl -s http://10.101.0.47:5000/api/envirophat/light/light
  name: Loft light status
#- platform: wunderground
#  api_key: !secret wunderground_key
#  monitored_conditions:
#    - alerts
#    - feelslike_c
#    - precip_today_metric
#    - pressure_mb
#    - relative_humidity
#    - temp_c
#    - temp_high_1d_c
#    - temp_low_1d_c
#    - wind_mph
#    - wind_string
#    - weather_1d_metric
#    - weather_1n_metric
#    - weather_2d_metric
#    - weather_2n_metric
#    - weather_3d_metric
#    - weather_3n_metric
#    - weather_4d_metric
#    - weather_4n_metric
- platform: time_date
  display_options:
    - time
- platform: worldtidesinfo
  name: Portsmouth Tides
  api_key: !secret worldtides_api_key
  latitude: 50.830573
  longitude: -1.105639
- platform: template
  sensors:
    simon_status:
      value_template: '{{ states.input_select.simon_status.state }}'
      friendly_name: 'Simon'
      entity_id: input_select.simon_status
    nikki_status:
      value_template: '{{ states.input_select.nikki_status.state }}'
      friendly_name: 'Nikki'
      entity_id: input_select.nikki_status
- platform: template
  sensors:
    aqara_last_change:
      value_template: "{% if as_timestamp(states.sensor.date__time.last_updated) - as_timestamp(states.sensor.illumination_7811dcb1f766.last_updated) > 5*60 %}true{% endif %}"
#- platform: template
#  sensors:
#    christmas_lights_power:
#      friendly_name: 'Christmas lights consumption'
#      value_template: '{{ states.switch.external_christmas_lights.attributes.current_consumption }}'
- platform: template
  sensors:
    door_loft_hatch:
      friendly_name: 'Loft hatch'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001bf6277', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001bf6277', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    door_front_door:
      friendly_name: 'Front door'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001a1f6b9', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001a1f6b9', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    door_patio_door:
      friendly_name: 'Patio door'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001a3e090', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001a3e090', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    window_living_room:
      friendly_name: 'Living room window'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001b70752', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001b70752', 'on') %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}
    window_kitchen_left:
      friendly_name: 'Kitchen window (left)'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001e4820c', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001e4820c', 'on') %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}
    window_kitchen_right:
      friendly_name: 'Kitchen window (right)'
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001de662f', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001de662f', 'on') %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}
- platform: zoneminder
  include_archived: false
###                ###
### battery levels ###
###                ###
- platform: template
  sensors:
    front_door_sensor_battery:
      friendly_name: 'Front door sensor battery'
      value_template: '{{ states.binary_sensor.door_window_sensor_158d0001a1f6b9.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: binary_sensor.door_window_sensor_158d0001a1f6b9
      device_class: battery
    patio_door_sensor_battery:
      friendly_name: 'Patio door sensor battery'
      value_template: '{{ states.binary_sensor.door_window_sensor_158d0001a3e090.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: binary_sensor.door_window_sensor_158d0001a3e090
      device_class: battery
    living_room_window_sensor_battery:
      friendly_name: 'Living room window sensor battery'
      value_template: '{{ states.binary_sensor.door_window_sensor_158d0001b70752.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: binary_sensor.door_window_sensor_158d0001b70752
      device_class: battery
    loft_hatch_sensor_battery:
      friendly_name: 'Loft hatch sensor battery'
      value_template: '{{ states.binary_sensor.door_window_sensor_158d0001bf6277.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: binary_sensor.door_window_sensor_158d0001bf6277
      device_class: battery
    kitchen_window_right_sensor_battery:
      friendly_name: 'Kitchen window (right) sensor battery'
      value_template: '{{ states.binary_sensor.door_window_sensor_158d0001de662f.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: binary_sensor.door_window_sensor_158d0001de662f
      device_class: battery
    kitchen_window_left_sensor_battery:
      friendly_name: 'Kitchen window (left) sensor battery'
      value_template: '{{ states.binary_sensor.door_window_sensor_158d0001e4820c.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: binary_sensor.door_window_sensor_158d0001e4820c
      device_class: battery
    understairs_cupboard_door_sensor_battery:
      friendly_name: 'Understairs cupboard door sensor battery'
      value_template: '{{ states.binary_sensor.door_window_sensor_158d000232ab79.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: binary_sensor.door_window_sensor_158d000232ab79
      device_class: battery
    kitchen_motion_sensor_battery:
      friendly_name: 'Kitchen motion sensor battery'
      value_template: '{{ states.binary_sensor.motion_sensor_158d000237acbc.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: binary_sensor.motion_sensor_158d000237acbc
      device_class: battery
    landing_switch_sensor_battery:
      friendly_name: 'Landing switch sensor battery'
      value_template: '{{ states.binary_sensor.switch_158d0001ef3aaa.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: binary_sensor.switch_158d0001ef3aaa
      device_class: battery
    ensuite_humidity_sensor_battery:
      friendly_name: 'Ensuite humidity sensor battery'
      value_template: '{{ states.sensor.humidity_158d0001fa5c1b.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: sensor.humidity_158d0001fa5c1b
      device_class: battery
