#- platform: command_line
#  switches:
#    energenie_one:
#      command_on: curl -s http://10.101.0.20:5000/api/energenie/1/1
#      command_off: curl -s http://10.101.0.20:5000/api/energenie/1/0
#      friendly_name: Drinks Cabinet
#    energenie_two:
#      command_on: curl -s http://10.101.0.20:5000/api/energenie/2/1
#      command_off: curl -s http://10.101.0.20:5000/api/energenie/2/0
#      friendly_name: Garden Room
#    energenie_three:
#      command_on: curl -s http://10.101.0.20:5000/api/energenie/3/1
#      command_off: curl -s http://10.101.0.20:5000/api/energenie/3/0
#      friendly_name: Firefly Lights
- platform: flux
  lights:
    - light.standard_lamp_left
    - light.standard_lamp_right
    - light.sideboard_bloom
  name: Flux Adjustment
  start_time: '18:00'
  stop_time: '23:00'
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1900
  brightness: 200
  disable_brightness_adjust: True
  mode: xy
- platform: mqtt
  name: "Loft Lighting"
  state_topic: "home/sonoff/loft/1/stat"
  command_topic: "home/sonoff/loft/1"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true
- platform: mqtt
  name: "Zigbee2mqtt main join"
  state_topic: "zigbee2mqtt/bridge/config/permit_join"
  command_topic: "zigbee2mqtt/bridge/config/permit_join"
  payload_on: "true"
  payload_off: "false"
