- platform: mqtt
  name: "Zigbee2mqtt main join"
  state_topic: "zigbee2mqtt/bridge/info"
  value_template: '{{ value_json.permit_join | lower }}'
  command_topic: "zigbee2mqtt/bridge/request/permit_join"
  payload_on: "true"
  payload_off: "false"
