title: Room 101
views:
  - title: Home
    icon: mdi:home-variant
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: At a glance
            entities:
              - sun.sun
              - sensor.loft_light_status
              - sensor.loft_temperature
          - type: entities
            title: Home Controls
            show_header_toggle: false
            entities:
              - input_boolean.night_mode_toggle
              - input_boolean.motion_lighting_toggle
              - entity: input_boolean.global_away_mode_toggle
                icon: mdi:account-off
                name: "Away: all automations"
              - entity: input_boolean.lighting_away_mode_toggle
                icon: mdi:lightbulb-outline
                name: "Away: lighting only"
              - entity: input_boolean.heating_away_mode_toggle
                icon: mdi:radiator
                name: "Away: heating only"
              - input_boolean.party_mode
      - type: vertical-stack
        cards:
          - type: entities
            title: Device Trackers
            entities:
              - device_tracker.houston
              - device_tracker.galaxys8
              - binary_sensor.people_home
              - input_select.simon_status
              - input_select.nikki_status
          - type: history-graph
            title: Occupancy
            entities:
              - binary_sensor.people_home
  - title: Security
    icon: mdi:security
    cards:
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: binary_sensor.people_home
                state: "off"
            card:
              type: picture-entity
              show_name: false
              show_state: false
              entity: camera.kitchen
          - type: conditional
            conditions:
              - entity: binary_sensor.people_home
                state: "off"
            card:
              type: picture-entity
              show_name: false
              show_state: false
              entity: camera.living_room
      - type: vertical-stack
        cards:
          - type: picture-entity
            title: Front CCTV
            show_name: false
            show_state: false
            entity: camera.exterior__front
          - type: picture-entity
            title: Rear CCTV
            show_name: false
            show_state: false
            entity: camera.exterior__rear
      - type: vertical-stack
        cards:
          - type: history-graph
            title: Front door 
            entities:
              - sensor.door_front_door
          - type: history-graph
            title: Patio doors
            entities:
              - sensor.door_patio_door
          - type: history-graph
            title: Living room window
            entities:
              - sensor.window_living_room
          - type: history-graph
            title: Kitchen window (left)
            entities:
              - sensor.window_kitchen_left
          - type: history-graph
            title: Kitchen window (right)
            entities:
              - sensor.window_kitchen_right
          - type: history-graph
            title: Loft hatch
            entities:
              - sensor.door_loft_hatch
      - type: entities
        title: Motion Sensors
        entities:
          - entity: binary_sensor.motion_sensor_158d000237acbc
            icon: mdi:run-fast
      - type: entities
        title: Holiday Mode
        show_header_toggle: false
        entities:
          - entity: input_boolean.holiday_mode
            icon: mdi:airplane-takeoff
  - title: Media
    icon: mdi:movie
    cards:
      - type: vertical-stack
        cards:
          - type: media-control
            entity: media_player.samsung_tv_remote
          - type: media-control
            entity: media_player.denon_avrx2100w
          - type: entities
            entities:
              - switch.tv_power
      - type: vertical-stack
        cards:
          - type: media-control
            entity: media_player.kitchen
          - type: media-control
            entity: media_player.living_room
          - type: media-control
            entity: media_player.garden_room
      - type: vertical-stack
        cards:
          - type: media-control
            entity: media_player.chromecast101
          - type: media-control
            entity: media_player.upstairs
          - type: media-control
            entity: media_player.kodi
      - type: entities
        title: Plex
        entities:
          - media_player.plex_6ckun1j8g0we34orzv4n9v7l
          - sensor.plex
      - type: entities
        title: Kodi Controls
        show_header_toggle: false
        entities:
          - input_boolean.lounge_media_dim_enable
          - input_number.kodi_dimmer_slider
          - input_boolean.kodi_amp_trigger
  - title: Lighting
    icon: mdi:lightbulb-outline
    cards:
      - type: entities
        title: All Lights
        show_header_toggle: false
        entities:
          - group.lounge_lights
          - group.energenie_switches
          - group.kitchen_lights
      - type: entities
        title: Lounge Lights
        show_header_toggle: false
        entities:
          - group.lounge_hues
          - switch.energenie_one
          - switch.energenie_two
          - switch.energenie_three
      - type: entities
        title: Sockets
        show_header_toggle: false
        entities:
          - switch.energenie_one
          - switch.energenie_two
          - switch.energenie_three
      - type: vertical-stack
        cards:
          - type: entities
            title: Kitchen Lights
            show_header_toggle: false
            entities:
              - light.kitchen_cabinets
          - type: sensor
            entity: sensor.illumination_158d000237acbc
            name: Kitchen illumination
            unit: lux
      - type: entities
        title: Lighting Control
        show_header_toggle: false
        entities:
          - switch.flux_adjustment
      - type: entities
        title: Loft Lighting
        show_header_toggle: false
        entities:
          - switch.loft_lighting
          - sensor.loft_light_status
          - sensor.door_loft_hatch
      - type: entities
        title: Understairs Lighting
        entities:
          - light.gateway_light_7811dcb1f766
  - title: Climate
    icon: mdi:thermometer-lines
    cards:
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.living_room
          - type: entities
            title: Downstairs Heating
            entities:
              - climate.living_room
              - sensor.living_room_thermostat_operation_mode
              - sensor.living_room_thermostat_humidity
              - binary_sensor.living_room_thermostat_has_leaf
              - binary_sensor.living_room_thermostat_online
              - binary_sensor.living_room_thermostat_is_locked
              - binary_sensor.living_room_thermostat_is_using_emergency_heat
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.master_bedroom
          - type: entities
            title: Upstairs Heating
            entities:
              - climate.master_bedroom
              - sensor.master_bedroom_thermostat_operation_mode
              - sensor.master_bedroom_thermostat_humidity
              - binary_sensor.master_bedroom_thermostat_has_leaf
              - binary_sensor.master_bedroom_thermostat_online
              - binary_sensor.master_bedroom_thermostat_is_locked
              - binary_sensor.master_bedroom_thermostat_is_using_emergency_heat
      - type: vertical-stack
        cards:
          - type: gauge
            title: Ensuite Temperature
            entity: sensor.temperature_158d0001fa5c1b
            unit_of_measurement: ""
            min: 0
            max: 30
          - type: entities
            title: Ensuite Bathroom
            entities:
              - sensor.temperature_158d0001fa5c1b
              - sensor.humidity_158d0001fa5c1b
  - title: Weather
    icon: mdi:umbrella
    cards:
      - type: entities
        title: 4-day Forecast
        entities:
          - sensor.pws_weather_1d_metric
          - sensor.pws_weather_1n_metric
          - sensor.pws_weather_2d_metric
          - sensor.pws_weather_2n_metric
          - sensor.pws_weather_3d_metric
          - sensor.pws_weather_3n_metric
          - sensor.pws_weather_4d_metric
          - sensor.pws_weather_4n_metric
      - type: iframe
        url: https://embed.windy.com/embed2.html?lat=51.055&lon=-0.330&zoom=6&level=surface&overlay=rain&menu=&message=true&marker=&calendar=&pressure=true&type=map&location=coordinates&detail=&detailLat=51.077&detailLon=-0.334&metricWind=mph&metricTemp=%C2%B0C&radarRange=-1
      - type: entities
        title: Current weather
        entities:
          - sensor.pws_temp_c
          - sensor.pws_feelslike_c
          - sensor.pws_temp_high_1d_c
          - sensor.pws_temp_low_1d_c
          - sensor.pws_precip_today_metric
          - sensor.pws_relative_humidity
          - sensor.pws_wind_mph
          - sensor.pws_wind_string
  - title: Infrastructure
    icon: mdi:cloud
    cards:
      - type: entities
        title: HA Travis Builds
        entities:
          - sensor.analbeardhomeassistant_state
          - sensor.analbeardhomeassistant_last_build_started_at
          - sensor.analbeardhomeassistant_last_build_duration
      - type: vertical-stack
        cards:
          - type: gauge
            entity: sensor.speedtest_download
            title: Speedtest (rx)
            unit_of_measurement: "Mb/s"
            min: 0
            max: 80
          - type: gauge
            entity: sensor.speedtest_upload
            title: Speedtest (tx))
            unit_of_measurement: "Mb/s"
            min: 0
            max: 22
          - type: sensor
            entity: sensor.speedtest_ping
            title: Ping
            icon: mdi:speedometer
            graph: line
#   - title:
#     icon: mdi:
#     cards:
#       - type:
#         title:
#         entities:
#           -
