title: Room 101
views:
  - title: Home
    icon: mdi:home-variant
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: At a glance
            entities:
              - sun.sun
              - sensor.loft_light_status
              - sensor.loft_temperature
          - type: history-graph
            title: Occupancy
            entities:
              - binary_sensor.people_home
      - type: vertical-stack
        cards:
          - type: entities
            title: Device Trackers
            show_header_toggle: false
            entities:
              - device_tracker.houston
              - device_tracker.galaxys8
              - binary_sensor.people_home
              - input_select.simon_status
              - input_select.nikki_status
      - type: vertical-stack
        cards:
          - type: entities
            title: Home Controls
            show_header_toggle: false
            entities:
              - input_boolean.house_lighting_toggle
              - input_boolean.motion_lighting_toggle
              - entity: input_boolean.global_away_mode_toggle
                icon: mdi:account-off
                name: "Away: all automations"
              - entity: input_boolean.lighting_away_mode_toggle
                icon: mdi:lightbulb-outline
                name: "Away: lighting only"
              - entity: input_boolean.heating_away_mode_toggle
                icon: mdi:radiator
                name: "Away: heating only"
      - type: vertical-stack
        cards:
          - type: entities
            title: Misc Controls
            show_header_toggle: false
            entities:
              - input_boolean.night_mode_toggle
              - entity: switch.desk_power
                icon: mdi:desktop-classic
                name: "Desk power"
              - input_boolean.party_mode
                #     - type: entity-filter
                #        entities:
                #          - sensor.ensuite_humidity_sensor_battery
                #          - sensor.front_door_sensor_battery
                #          - sensor.kitchen_motion_sensor_battery
                #          - sensor.kitchen_window_left_sensor_battery
                #          - sensor.kitchen_window_right_sensor_battery
                #          - sensor.landing_switch_sensor_battery
                #          - sensor.living_room_window_sensor_battery
                #          - sensor.loft_hatch_sensor_battery
                #          - sensor.patio_door_sensor_battery
                #          - sensor.understairs_cupboard_door_sensor_battery
                #        state_filter:
                #          - "10.0"
                #          - "9.0"
                #          - "8.0"
                #          - "7.0"
                #          - "6.0"
                #          - "5.0"
                #          - "4.0"
                #          - "3.0"
                #          - "2.0"
                #          - "1.0"
                #          - "0.0"
                #        show_empty: false
                #        card:
                #          type: glance
                #          title: Low batteries
  - title: Security
    icon: mdi:security
    cards:
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: binary_sensor.people_home
                state: "off"
            card:
              type: picture-entity
              show_name: false
              show_state: false
              entity: camera.kitchen
          - type: conditional
            conditions:
              - entity: binary_sensor.people_home
                state: "off"
            card:
              type: picture-entity
              show_name: false
              show_state: false
              entity: camera.living_room
      - type: vertical-stack
        cards:
          - type: picture-entity
            title: Front CCTV
            show_name: false
            show_state: false
            entity: camera.exterior_front
          - type: picture-entity
            title: Rear CCTV
            show_name: false
            show_state: false
            entity: camera.exterior_rear
          - type: picture-entity
            title: Front door
            show_name: false
            show_state: false
            entity: camera.uvc_g3_door
      - type: vertical-stack
        cards:
          - type: history-graph
            title: Front door 
            entities:
              - sensor.door_front_door
          - type: history-graph
            title: Patio doors
            entities:
              - sensor.door_patio_door
          - type: history-graph
            title: Living room window
            entities:
              - sensor.window_living_room
          - type: history-graph
            title: Kitchen window (left)
            entities:
              - sensor.window_kitchen_left
          - type: history-graph
            title: Kitchen window (right)
            entities:
              - sensor.window_kitchen_right
          - type: history-graph
            title: Loft hatch
            entities:
              - sensor.door_loft_hatch
      - type: vertical-stack
        cards:
          - type: entities
            title: Motion Sensors
            show_header_toggle: false
            entities:
              - entity: binary_sensor.motion_sensor_158d000237acbc
                icon: mdi:run-fast
              - entity: binary_sensor.motion_sensor_158d0002b7f000
                icon: mdi:run-fast
          - type: history-graph
            title: Kitchen motion sensor
            entities:
              - binary_sensor.motion_sensor_158d000237acbc
          - type: history-graph
            title: Living room motion sensor
            entities:
              - binary_sensor.motion_sensor_158d0002b7f000
      - type: entities
        title: Holiday Mode
        show_header_toggle: false
        entities:
          - entity: input_boolean.holiday_mode
            icon: mdi:airplane-takeoff
  - title: Media
    icon: mdi:movie
    cards:
      - type: vertical-stack
        cards:
          - type: media-control
            entity: media_player.samsung_tv_remote
          - type: media-control
            entity: media_player.denon_avrx2100w
      - type: vertical-stack
        cards:
          - type: media-control
            entity: media_player.kitchen
          - type: media-control
            entity: media_player.living_room
          - type: media-control
            entity: media_player.garden_room
      - type: vertical-stack
        cards:
          - type: media-control
            entity: media_player.chromecast101
          - type: media-control
            entity: media_player.upstairs
          - type: media-control
            entity: media_player.kodi
      - type: entities
        title: Plex
        entities:
          - media_player.plex_6ckun1j8g0we34orzv4n9v7l
          - sensor.plex
      - type: entities
        title: Kodi Controls
        show_header_toggle: false
        entities:
          - input_boolean.lounge_media_dim_enable
          - input_number.kodi_dimmer_slider
          - input_boolean.kodi_amp_trigger
  - title: Lighting
    icon: mdi:lightbulb-outline
    cards:
      - type: entities
        title: All Lights
        show_header_toggle: false
        entities:
          - group.lounge_lights
          - group.kitchen_lights
      - type: vertical-stack
        cards:
          - type: entities
            title: Lounge Lights
            show_header_toggle: false
            entities:
              - group.lounge_hues
          - type: sensor
            entity: sensor.illumination_158d0002b7f000
            name: Living room illumination
            unit: lux
          - type: entities
            title: Sockets
            entities:
              - switch.bookcase_lights
              - switch.twigs
      - type: vertical-stack
        cards:
          - type: entities
            title: Kitchen Lights
            show_header_toggle: false
            entities:
              - light.kitchen_cabinets
          - type: sensor
            entity: sensor.illumination_158d000237acbc
            name: Kitchen illumination
            unit: lux
          - type: entities
            title: Desk Power
            show_header_toggle: false
            entities:
              - switch.desk_power
      - type: entities
        title: Lighting Control
        show_header_toggle: false
        entities:
          - switch.flux_adjustment
      - type: entities
        title: Loft Lighting
        show_header_toggle: false
        entities:
          - switch.loft_lighting
          - sensor.loft_light_status
          - sensor.door_loft_hatch
      - type: entities
        title: Understairs Lighting
        show_header_toggle: false
        entities:
          - light.gateway_light_7811dcb1f766
  - title: Climate
    icon: mdi:thermometer-lines
    cards:
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.living_room
          - type: entities
            title: Downstairs Heating
            show_header_toggle: false
            entities:
              - climate.living_room
              - sensor.living_room_thermostat_operation_mode
              - sensor.living_room_thermostat_humidity
              - binary_sensor.living_room_thermostat_has_leaf
              - binary_sensor.living_room_thermostat_online
              - binary_sensor.living_room_thermostat_is_locked
              - binary_sensor.living_room_thermostat_is_using_emergency_heat
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.master_bedroom
          - type: entities
            title: Upstairs Heating
            show_header_toggle: false
            entities:
              - climate.master_bedroom
              - sensor.master_bedroom_thermostat_operation_mode
              - sensor.master_bedroom_thermostat_humidity
              - binary_sensor.master_bedroom_thermostat_has_leaf
              - binary_sensor.master_bedroom_thermostat_online
              - binary_sensor.master_bedroom_thermostat_is_locked
              - binary_sensor.master_bedroom_thermostat_is_using_emergency_heat
      - type: vertical-stack
        cards:
          - type: gauge
            title: Ensuite Temperature
            entity: sensor.temperature_158d0001fa5c1b
            unit_of_measurement: ""
            min: 0
            max: 30
          - type: entities
            title: Ensuite Bathroom
            show_header_toggle: false
            entities:
              - sensor.temperature_158d0001fa5c1b
              - sensor.humidity_158d0001fa5c1b
  - title: Weather
    icon: mdi:umbrella
    cards:
      - type: iframe
        title: Rain map
        url: "https://embed.windy.com/embed2.html?lat=54.419&lon=-2.329&zoom=5&level=surface&overlay=rain&menu=&message=true&marker=&calendar=now&pressure=true&type=map&location=coordinates&detail=&detailLat=51.094&detailLon=-0.262&metricWind=default&metricTemp=default&radarRange=-1"
        aspect_ratio: 90%
      - type: iframe
        title: Wind map
        url: "https://embed.windy.com/embed2.html?lat=54.419&lon=-2.329&zoom=5&level=surface&overlay=wind&menu=&message=true&marker=&calendar=now&pressure=true&type=map&location=coordinates&detail=&detailLat=51.094&detailLon=-0.262&metricWind=default&metricTemp=default&radarRange=-1"
        aspect_ratio: 90%
      - type: entities
        title: Current weather
        show_header_toggle: false
        entities:
          - sensor.metoffice_weather
          - sensor.metoffice_temperature
          - sensor.metoffice_feels_like_temperature
          - sensor.metoffice_probability_of_precipitation
          - sensor.metoffice_wind_speed
          - sensor.metoffice_wind_gust
#   - title:
#     icon: mdi:
#     cards:
#       - type:
#         title:
#         entities:
#           -
