title: Room 101
views:
  - !include lovelace/00_home.yaml
  - !include lovelace/05_living_room.yaml
  - !include lovelace/10_kitchen.yaml
  - !include lovelace/15_bedroom.yaml
  - !include lovelace/20_office.yaml
  - !include lovelace/25_hall.yaml
  - !include lovelace/50_security.yaml
  - !include lovelace/99_admin.yaml
