title: Room 101
resources:
  - url: /local/monster-card/monster-card.js
    type: js
views:
  - !include lovelace/00_home.yaml
  - !include lovelace/05_security.yaml
  - !include lovelace/10_media.yaml
  - !include lovelace/15_lighting.yaml
  - !include lovelace/20_climate.yaml
  - !include lovelace/25_weather.yaml
