- platform: template
  sensors:
    people_home:
      value_template: >-
        {{ is_state('sensor.simon_status', 'home')
           or is_state('sensor.simon_status', 'just arrived')
           or is_state('sensor.simon_status', 'just left')
           or is_state('sensor.nikki_status', 'home')
           or is_state('sensor.nikki_status', 'just arrived')
           or is_state('sensor.nikki_status', 'just left') }}
# template sensors for calendar event offsets - used for conditional lovelace templating
- platform: template
  sensors:
    recycling_bin_offset:
      value_template: "{{ state_attr('calendar.recycling_bin','offset_reached') }}"
    waste_bin_offset:
      value_template: "{{ state_attr('calendar.waste_bin','offset_reached') }}"
