- alias: "Turn off all lights"
  trigger:
    - platform: state
      entity_id: device_tracker.simon, device_tracker.nikki
      from: 'home'
      to: 'not_home'
  action:
    service: light.turn_off
    entity_id:
      - group.automation_all_lights
