- alias: "Turn off all lights"
  trigger:
    - platform: state
      entity_id: group.people
      from: 'home'
      to: 'not_home'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.global_away_mode_toggle
        state: 'on'
      - condition: state
        entity_id: input_boolean.lighting_away_mode_toggle
        state: 'on'
  action:
    service: light.turn_off
    entity_id:
      - group.automation_all_lights
