- alias: "Turn off all lights"
  trigger:
    - platform: state
      entity_id: group.people
      from: 'home'
      to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.away_mode_enable
    state: 'on'
  action:
    service: light.turn_off
    entity_id:
      - group.automation_all_lights
