- alias: "Apple watch: temperature report"
  mode: parallel
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Temperature report
  action:
    - variables:
        iphone: "notify.mobile_app_{{ trigger.event.data.sourceDeviceName.replace('-', '_') }}"
    - service: "{{ iphone }}"
      data:
        title: "Temperature"
        message: >
          Upstairs: {{ states('sensor.master_bedroom_temperature') }}°C ({{ state_attr('climate.master_bedroom', 'hvac_action') }}) ||
          Downstairs: {{ states('sensor.living_room_temperature') }}°C ({{ state_attr('climate.living_room', 'hvac_action') }}) ||
          Nursery: {{ states('sensor.0x00158d0007e2074f_temperature') }}°C
- alias: "Apple watch: set downstairs temperature"
  mode: parallel
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Downstairs temperature
  action:
    - variables:
        iphone: "notify.mobile_app_{{ trigger.event.data.sourceDeviceName.replace('-', '_') }}"
    - service: "{{ iphone }}"
      data:
        message: "Downstairs temperature"
        data:
          actions:
            - action: T18
              title: "18"
            - action: T19
              title: "19"
            - action: T20
              title: "20"
            - action: T21
              title: "21"
    - wait_for_trigger:
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: T18
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: T19
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: T20
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: T21
      timeout: "00:00:20"
      continue_on_timeout: false
    - variables:
        temperature: "{{ wait.trigger.event.data.action.split('T')[1] | int }}"
    - service: climate.set_temperature
      data:
        entity_id: climate.living_room
        temperature: "{{ temperature }}"
- alias: "Apple watch: set upstairs temperature"
  mode: parallel
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Upstairs temperature
  action:
    - variables:
        iphone: "notify.mobile_app_{{ trigger.event.data.sourceDeviceName.replace('-', '_') }}"
    - service: "{{ iphone }}"
      data:
        message: "Upstairs temperature"
        data:
          actions:
            - action: T18
              title: "18"
            - action: T19
              title: "19"
            - action: T20
              title: "20"
            - action: T21
              title: "21"
    - wait_for_trigger:
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: T18
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: T19
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: T20
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: T21
      timeout: "00:00:20"
      continue_on_timeout: false
    - variables:
        temperature: "{{ wait.trigger.event.data.action.split('T')[1] | int }}"
    - service: climate.set_temperature
      data:
        entity_id: climate.master_bedroom
        temperature: "{{ temperature }}"
- alias: "Apple watch: nursery lights dim"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "Nursery (dim)"
  action:
    service: scene.turn_on
    target:
      entity_id: scene.nursery_james
- alias: "Apple watch: nursery lights off"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "Nursery (off)"
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.hue_color_lamp_1_3
        - light.hue_color_lamp_1_2
