- alias: "Apple watch: temperature report"
  mode: parallel
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Current temps
  action:
    - variables:
        iphone: "notify.mobile_app_{{ trigger.event.data.sourceDeviceName.replace('-', '_') }}"
    - service: "{{ iphone }}"
      data:
        title: "Temperature"
        message: >
          Upstairs: {{ states('sensor.master_bedroom_temperature') }}°C ({{ state_attr('climate.master_bedroom', 'hvac_action') }}) ||
          Downstairs: {{ states('sensor.living_room_temperature') }}°C ({{ state_attr('climate.living_room', 'hvac_action') }}) ||
          Nursery: {{ states('sensor.0x00158d0007e2074f_temperature') }}°C
- alias: "Apple watch: set downstairs temperature"
  mode: parallel
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Set downstairs temp
  action:
    - variables:
        iphone: "notify.mobile_app_{{ trigger.event.data.sourceDeviceName.replace('-', '_') }}"
    - service: "{{ iphone }}"
      data:
        message: "Downstairs temperature"
        data:
          actions:
            - action: T18
              title: "18"
            - action: T19
              title: "19"
            - action: T20
              title: "20"
            - action: T21
              title: "21"
    - wait_for_trigger:
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: T18
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: T19
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: T20
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: T21
      timeout: "00:00:20"
      continue_on_timeout: false
    - variables:
        temperature: "{{ wait.trigger.event.data.action.split('T')[1] | int }}"
    - service: climate.set_temperature
      data:
        entity_id: climate.living_room
        temperature: "{{ temperature }}"
- alias: "Apple watch: set upstairs temperature"
  mode: parallel
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Set upstairs temp
  action:
    - variables:
        iphone: "notify.mobile_app_{{ trigger.event.data.sourceDeviceName.replace('-', '_') }}"
    - service: "{{ iphone }}"
      data:
        message: "Upstairs temperature"
        data:
          actions:
            - action: T18
              title: "18"
            - action: T19
              title: "19"
            - action: T20
              title: "20"
            - action: T21
              title: "21"
    - wait_for_trigger:
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: T18
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: T19
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: T20
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: T21
      timeout: "00:00:20"
      continue_on_timeout: false
    - variables:
        temperature: "{{ wait.trigger.event.data.action.split('T')[1] | int }}"
    - service: climate.set_temperature
      data:
        entity_id: climate.master_bedroom
        temperature: "{{ temperature }}"
- alias: "Apple watch: nursery lights dim"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "Nursery (dim)"
  action:
    service: scene.turn_on
    target:
      entity_id: scene.nursery_james
- alias: "Apple watch: nursery lights off"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "Nursery (off)"
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.hue_color_lamp_1_3
        - light.hue_color_lamp_1_2

## living room
- alias: "Apple watch: living room lights dim"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "Lounge (dim)"
  action:
    service: scene.turn_on
    target:
      entity_id: scene.living_room_relax
- alias: "Apple watch: living room lights bright"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "Lounge (bright)"
  action:
    service: scene.turn_on
    target:
      entity_id: scene.living_room_champagne
- alias: "Apple watch: living roomlights off"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "Lounge (off)"
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.standard_lamp_left
        - light.standard_lamp_right
        - light.garden_room_lamp
        - light.sideboard_bloom_left
        - light.sideboard_bloom_right

## kitchen
- alias: "Apple watch: kitchen daytime lights"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "Kitchen (day)"
  action:
    service: scene.turn_on
    target:
      entity_id: scene.kitchen_concentrate
- alias: "Apple watch: kitchen nightime lights"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "Kitchen (night)"
  action:
    service: scene.turn_on
    target:
      entity_id: scene.kitchen_tropical_twilight
- alias: "Apple watch: kitchen undercabinet lights on"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "Undercabinet lights on"
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.0x00124b0024c04605
- alias: "Apple watch: kitchen undercabinet lights off"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "Undercabinet lights off"
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.0x00124b0024c04605

## office lighting
- alias: "Apple watch: office lights bright"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "Office (bright)"
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.office_standard_lamp
        - light.0x000d6ffffe07b722
      brightness_pct: "100"
- alias: "Apple watch: office lights work"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "Office (work)"
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.office_standard_lamp
        - light.0x000d6ffffe07b722
      brightness_pct: "100"
- alias: "Apple watch: office lights off"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "Office lights off"
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.office_standard_lamp
        - light.office_ceiling_lamp
        - light.0x000d6ffffe07b722
- alias: Apple watch camera stream
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: "Nursery camera"
      id: nursery
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: "Front door camera"
      id: frontdoor
  condition: []
  action:
    - service: notify.mobile_app_houston
      data:
        data:
          entity_id: |
            {% if trigger.id == 'nursery' %}
              camera.nursery2
            {% elif trigger.id == 'frontdoor' %}
              camera.door
            {% endif %}
          push:
            sound: none
          tag: livestream
        message: |
          {% if trigger.id == 'nursery' %}
            Nursery
          {% elif trigger.id == 'frontdoor' %}
            Front door
          {% endif %}
  mode: single
