- alias: 'Disable holiday mode'
  trigger:
    platform: state
    entity_id: device_tracker.simon, device_tracker.nikki
    from: 'not_home'
    to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.holiday_mode
    state: 'on'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.holiday_mode
