- alias: "Kodi - power on amp"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      to: 'playing'
  condition:
    - condition: state
      entity_id: media_player.denon_avrx2100w
      state: 'off'
  action:
    - service: notify.kodi_notifier
      data:
        title: "Home Assistant"
        message: "Pausing to wake amp"
        data:
          displaytime: 5000
          icon: "info"
    - service: media_player.media_play_pause
      entity_id: media_player.kodi
    - service: media_player.turn_on
      entity_id: media_player.denon_avrx2100w
    - delay:
        seconds: 10
    - service: media_player.media_play_pause
      entity_id: media_player.kodi
