#
# Turn internal christmas lights on at sunset
#
- alias: "Turn on internal christmas lights"
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.people
        state: 'home'
      - condition: state
        entity_id: switch.energenie_two
        state: 'off'
  action:
    service: switch.turn_on
    entity_id:
      - switch.energenie_two
#
# Turn internal christmas lights on when we arrive
#
- alias: "Internal christmas lights on (arrival)"
  trigger:
    - platform: state
      entity_id: group.people
      from: 'not_home'
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: 'sunset'
      - condition: state
        entity_id: switch.energenie_two
        state: 'off'
  action:
    service: switch.turn_on
    entity_id:
      - switch.energenie_two
#
# Turn internal christmas lights off when we leave
#
- alias: 'Turn off internal christmas lights'
  trigger:
    platform: state
    entity_id: group.automation_people_status
    from: 'just left'
    to: 'away'
  action:
    service: switch.turn_off
    entity_id: switch.energenie_two
