#
# Turns off al lights when we leave the house
#
- alias: "Turn off all lights"
  trigger:
    platform: state
    entity_id: binary_sensor.people_home
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.global_away_mode_toggle
        state: 'on'
      - condition: state
        entity_id: input_boolean.lighting_away_mode_toggle
        state: 'on'
  action:
    service: light.turn_off
    entity_id:
      - group.automation_all_lights
#
# Turns off loft lights after an hour
#
- alias: 'Turn loft light off'
  trigger:
    - platform: state
      entity_id: sensor.loft_light_status
      to: 'on'
      for:
        hours: 1
  action:
    service: switch.turn_off
    entity_id: switch.loft_lighting
