- alias: 'Turn loft light off'
  trigger:
    - platform: state
      entity_id: sensor.loft_light_status
      to: 'on'
      for:
        hours: 1
  action:
    service: switch.turn_off
    entity_id: switch.loft_lighting
