# powers on living room amp and sets input when the Sonos
# connect starts playing
- alias: "Sonos - power on amp"
  trigger:
    - platform: state
      entity_id: media_player.living_room
      to: 'playing'
  condition:
    - condition: state
      entity_id: media_player.denon_avrx2100w
      state: 'off'
  action:
    - service: media_player.turn_on
      entity_id: media_player.denon_avrx2100w
    - delay:
        seconds: 10
    - service: media_player.select_source
      data:
        entity_id: media_player.denon_avrx2100w
        source: 'Media Player'
    - service: media_player.volume_set
      data:
        entity_id: media_player.denon_avrx2100w
        volume_level: 0.5
#
# Dims living room Hues when Kodi transitions to playing
#
- alias: "Kodi - Playing"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      to: 'playing'
      for:
        seconds: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: input_boolean.lounge_media_dim_enable
        state: 'on'
      - condition: state
        entity_id: group.lounge_hues
        state: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: group.lounge_hues
      brightness_pct: '{{ states.input_number.kodi_dimmer_slider.state | int }}'
      transition: '2'
#
# Dims living room Hues when Kodi transitions to playing
#
- alias: "Kodi - already playing"
  trigger:
    - platform: state
      entity_id: group.lounge_hues
      to: 'on'
  condition:
    - condition: state
      entity_id: media_player.living_room
      state: 'playing'
  action:
    service: light.turn_on
    data:
      entity_id: group.lounge_hues
      brightness_pct: '{{ states.input_number.kodi_dimmer_slider.state | int }}'
      transition: '2'
#
# Sets living room Hue brightness down if Kodi is already playing
# and the Hues are turned on
#
- alias: "Kodi - Paused"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      to: 'paused'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: input_boolean.lounge_media_dim_enable
        state: 'on'
      - condition: state
        entity_id: group.lounge_hues
        state: 'on'
  action:
    service: light.turn_on
    entity_id: group.lounge_hues
    data:
      brightness_pct: '50'
      transition: '3'
#
# Resets living room Hues when Kodi transitions to stopped
#
- alias: "Kodi - Stopped"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      from: 'playing'
      to: 'idle'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: input_boolean.lounge_media_dim_enable
        state: 'on'
      - condition: state
        entity_id: group.lounge_hues
        state: 'on'
  action:
    service: light.turn_on
    entity_id: group.lounge_hues
    data:
      brightness_pct: '80'
      transition: '3'
#
# Turn on living room amp if Kodi transitions to playing
#
- alias: "Kodi - power on amp"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      to: 'playing'
  condition:
    - condition: state
      entity_id: media_player.denon_avrx2100w
      state: 'off'
  action:
    - service: notify.kodi_notifier
      data:
        title: "Home Assistant"
        message: "Pausing to wake amp"
        data:
          displaytime: 5000
          icon: "info"
    - service: media_player.media_play_pause
      entity_id: media_player.kodi
    - service: media_player.turn_on
      entity_id: media_player.denon_avrx2100w
    - delay:
        seconds: 10
    - service: media_player.media_play_pause
      entity_id: media_player.kodi
