- alias: "Kodi - already playing"
  trigger:
    - platform: state
      entity_id: group.lounge_hues
      to: 'on'
  condition:
    - condition: state
      entity_id: media_player.living_room
      state: 'playing'
  action:
    service: light.turn_on
    data:
      entity_id: group.lounge_hues
      brightness_pct: '{{ states.input_slider.kodi_dimmer_slider.state | int }}'
      transition: '2'
