#
# Set thermostats to away mode when we leave
#
- alias: 'Set Nests to away mode'
  trigger:
    platform: state
    entity_id: binary_sensor.people_home
    to: 'off'
  action:
    - service: nest.set_mode
      data:
        home_mode: away
    - service: notify.slack_connector
      data:
        message: Nest set to away mode
#
# Set thermostats to home mode when we arrive
#
- alias: 'Set Nest to home mode'
  trigger:
    platform: state
    entity_id: binary_sensor.people_home
    to: 'on'
  action:
    - service: nest.set_mode
      data:
        home_mode: home
    - service: notify.slack_connector
      data:
        message: Nest set to home mode
