#
# Set thermostats to away mode when we leave
#
- alias: 'Set Nests to away mode'
  trigger:
    - platform: state
      entity_id: sensor.simon_status
      to: 'away'
    - platform: state
      entity_id: sensor.nikki_status
      to: 'away'
  condition:
    condition: state
    entity_id: group.people
    state: 'not_home'
  action:
    - service: nest.set_mode
      data:
        home_mode: away
    - service: notify.slack_connector
      data:
        message: Nest set to away mode
#
# Set thermostats to home mode when we arrive
#
- alias: 'Set Nest to home mode'
  trigger:
    - platform: state
      entity_id: sensor.simon_status
      to: 'just arrived'
    - platform: state
      entity_id: sensor.nikki_status
      to: 'just arrived'
  condition:
    condition: state
    entity_id: group.people
    state: 'home'
  action:
    - service: nest.set_mode
      data:
        home_mode: home
    - service: notify.slack_connector
      data:
        message: Nest set to home mode
