#
# Disable holiday mode on our return
#
- alias: 'Disable holiday mode'
  trigger:
    platform: state
    entity_id: binary_sensor.people_home
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.holiday_mode
    state: 'on'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.holiday_mode
