- alias: "Sonos - power on amp"
  trigger:
    - platform: state
      entity_id: media_player.living_room
      to: 'playing'
  condition:
    - condition: state
      entity_id: media_player.denon_avrx2100w
      state: 'off'
  action:
    - service: media_player.turn_on
      entity_id: media_player.denon_avrx2100w
    - delay:
        seconds: 10
    - service: media_player.select_source
      data:
        entity_id: media_player.denon_avrx2100w
        source: 'Media Player'
    - service: media_player.volume_set
      data:
        entity_id: media_player.denon_avrx2100w
        volume_level: 0.5
