name: 'check home-assistant configuration'
on:
  pull_request_target:
  workflow_dispatch:
jobs:
  debug_info:
    name: 'print debug info'
    runs-on: ubuntu-latest
    steps:
      - name: Print github context JSON
        run: |
          cat <<EOF
          ${{ toJson(github) }}
          EOF
