name: 'check configuration'
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:
jobs:
  pullrequest:
    name: 'check on PR'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: 'workaround for nektos/act'
        run: |
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: 'checkout'
        uses: actions/checkout@v2
      - run: mv secrets secrets.old || true
      - run: mkdir secrets
      - run: cp -v ci/secrets.yaml secrets.yaml
      - run: cp -v ci/google-cloud-tts.json secrets/google-cloud-tts.json
      - run: cp -v ci/google-assistant.json secrets/google-assistant.json
      - name: 'yamllint'
        id: lint
        uses: ibiqlik/action-yamllint@v1
        with:
          config_file: ci/yamllint.yml
        continue-on-error: true
      - name: 'check config'
        id: check
        uses: glitchcrab/action-hass-check-config@v0.0.1
        with:
          version: "2021.1.5"
        continue-on-error: true
      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `yamllint: ${{ steps.lint.outcome }}
            config check: ${{ steps.check.outcome }}`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: 'fail if lint or check fails'
        if: steps.lint.outcome == 'failure' || steps.check.outcome == 'failure'
        run: exit 1
  mergedpullrequest:
    name: 'check on merge'
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: 'workaround for nektos/act'
        run: |
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: 'checkout'
        uses: actions/checkout@v2
      - run: mv secrets secrets.old || true
      - run: mkdir secrets
      - run: cp -v ci/secrets.yaml secrets.yaml
      - run: cp -v ci/google-cloud-tts.json secrets/google-cloud-tts.json
      - run: cp -v ci/google-assistant.json secrets/google-assistant.json
      - name: 'yamllint'
        id: lint
        uses: ibiqlik/action-yamllint@v1
        with:
          config_file: ci/yamllint.yml
      - name: 'check config'
        id: check
        uses: glitchcrab/action-hass-check-config@v0.0.1
        with:
          version: "2021.1.5"
