name: 'check configuration'
on: pull_request

jobs:
  plan:
    name: 'test'
    runs-on: ubuntu-latest
    steps:
      - run: |
          # Hack to get setup-python to work on act
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: 'checkout'
        uses: actions/checkout@v2
      - run: mv ci/secrets.yaml secrets.yaml
      - run: mv ci/google-cloud-tts.json secrets/google-cloud-tts.json
      - name: 'yamllint'
        uses: ibiqlik/action-yamllint@v1
        with:
          config_file: ci/yamllint.yml
      - name: Run Config Check
        uses: ludeeus/action-ha-config-check@master
