name: 'check on merge'
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  check:
    name: 'check master'
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - run: |
          # Hack to get setup-python to work on act
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: 'checkout'
        uses: actions/checkout@v2
      - run: mv secrets secrets.old || true
      - run: mkdir secrets
      - run: cp -v ci/secrets.yaml secrets.yaml
      - run: cp -v ci/google-cloud-tts.json secrets/google-cloud-tts.json
      - name: 'yamllint'
        uses: ibiqlik/action-yamllint@v1
        with:
          config_file: ci/yamllint.yml
      - uses: glitchcrab/action-hass-check-config@v0.0.1
        with:
          version: "2020.12.2"
