name: 'lint yaml'
on:
  pull_request_target:
  workflow_dispatch:
jobs:
  debug_info:
    name: 'print debug info'
    runs-on: ubuntu-latest
    steps:
      - name: Print github context JSON
        run: |
          cat <<EOF
          ${{ toJson(github) }}
          EOF
  yamllint:
    name: 'lint yamls'
    runs-on: ubuntu-latest
    steps:
      - name: 'workaround for nektos/act'
        run: |
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: 'checkout'
        uses: actions/checkout@v2
      - name: 'yamllint'
        id: lint
        uses: ibiqlik/action-yamllint@v3.1
        with:
          config_file: ci/yamllint.yml
        continue-on-error: true
      - name: 'comment on PR'
        if: github.event_name == 'pull_request_target'
        uses: actions/github-script@v5
        with:
          script: |
            const commentContent = `yamllint: ${{ steps.lint.outcome }}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentContent
            })
      - name: 'fail if linting fails'
        if: steps.lint.outcome == 'failure'
        run: exit 1
